### PR TITLE
Support v4 experiment

### PR DESCRIPTION
**Pull request by k88hudson**
These commits add per-client requests and some new query types (e.g., `DS`).

### CODE REVIEW

**Review by ekr — APPROVED** [review]
Reviewed in ekr/ repo.

**Review by gabrielBusta — APPROVED** [review]

**Review by gabrielBusta — CHANGES_REQUESTED** [review]
Should we bump the version?

**Comment by gabrielBusta** [comment]
The version should be updated [here](https://github.com/mozilla-extensions/dnssec-interference/blob/master/package.json#L3) and [here](https://github.com/mozilla-extensions/dnssec-interference/blob/master/src/manifest.json#L5)

**Review by gabrielBusta — APPROVED** [review]
LGTM

**Pull request merged**
